Compile fixes for static QML modules
"helper" targets of kddockwidgetsTargets are not exported, which cause the install/export to fail in a subdirectory build.
Add missing resource file, which causes:
Undefined symbols for architecture arm64:
  "qInitResources_kddockwidgets_qtquick()", referenced from:
      gui_main(gui_args const&) in gui.cpp.o
      initResources() in libkddockwidgets-qt6.a[9](Platform.cpp.o)
ld: symbol(s) not found for architecture arm64